// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cneljermlocaxscsczor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuZWxqZXJtbG9jYXhzY3Njem9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDk2ODMsImV4cCI6MjA2OTIyNTY4M30.3nGJV_Lli1nGJQoRiEd15lYKBKGJBRgHXQjzv_hcMAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});